### ISSUE TITLE
duplicate sections in odml view

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/gogs#18]
The top level sections for some public odml files are displayed twice.
Eg https://web.gin.g-node.org/INT/multielectrode_grasp/src/master/datasets/i140703-001.odml is displayed as 
![image](https://user-images.githubusercontent.com/8088860/38554877-804122fe-3cc4-11e8-8e13-be5f9dc2804b.png)

**Comment by cgars** [comment]
Hey there

How nice that somebody is using (or rather discovered) the odML tree view. 

I've implemented it a while ago and then kind of thought ~~its mostly useless and ugly~~ does not have the highest priority  (as there are other alternatives... like odML View) and subsequently have not spent more time on it. 

Basically, the odMLs are decoded twice resulting in the symptoms you describe. Ill include a fix in this week's GIN upgrade.

Thanks again for reporting this back!

All the best
